### ISSUE TITLE
Unable to run java-resteasy-appclasses

### ISSUE THREAD

**Issue by davidklimek-afterpay** [swagger-api/swagger-samples#179]
I followed the instructions here:
```
https://github.com/swagger-api/swagger-samples/tree/2.0/java/java-resteasy-appclasses
```
Which ask you to run this command:
```
mvn package -Dlog4j.configuration=file:./conf/log4j.properties jetty:run
```

which produces this error:
```
...
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.519 s
[INFO] Finished at: 2019-06-24T19:26:09-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project swagger-java-resteasy-sample: Compilation failure: Compilation failure: 
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Any ideas what additional steps need to be taking?

**Comment by davidklimek-afterpay** [comment]
I added the following into the pom.xml.
```
    <properties>
        <maven.compiler.source>7</maven.compiler.source>
        <maven.compiler.target>7</maven.compiler.target>
    </properties>
```
But now I get this error.
```[main] ERROR o.j.r.p.providers.RegisterBuiltin - NoClassDefFoundError: Unable to load builtin provider: org.jboss.resteasy.plugins.providers.jaxb.json.JsonCollectionProvider
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3143) ~[na:na]
	at java.base/java.lang.Class.getConstructors(Class.java:1949) ~[na:na]
	at org.jboss.resteasy.util.PickConstructor.pickSingletonConstructor(PickConstructor.java:30) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.spi.ResteasyProviderFactory.getProviderInstance(ResteasyProviderFactory.java:1136) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.spi.ResteasyProviderFactory.addMessageBodyReader(ResteasyProviderFactory.java:480) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:834) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:70) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:31) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:219) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:67) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36) ~[resteasy-jaxrs-2.3.5.Final.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:534) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:346) ~[na:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:742) ~[na:na]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265) ~[na:na]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1252) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:710) ~[na:na]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) ~[na:na]
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:293) ~[jetty-maven-plugin-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[na:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172) ~[na:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[na:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) ~[na:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[na:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) ~[na:na]
	at org.eclipse.jetty.server.Server.doStart(Server.java:282) ~[na:na]
	at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65) ~[jetty-maven-plugin-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[na:na]
	at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:520) ~[jetty-maven-plugin-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:365) ~[jetty-maven-plugin-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:523) ~[jetty-maven-plugin-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137) ~[na:na]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210) ~[na:na]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156) ~[na:na]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148) ~[na:na]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117) ~[na:na]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81) ~[na:na]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56) ~[na:na]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) ~[na:na]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305) ~[na:na]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192) ~[na:na]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105) ~[na:na]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956) ~[na:na]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) ~[na:na]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282) ~[na:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225) ~[na:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406) ~[na:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347) ~[na:na]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[na:na]
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:421) ~[na:na]
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383) ~[na:na]
	... 56 common frames omitted

```
