### ISSUE TITLE
Error injecting constructor, java.lang.IllegalArgumentException: Unrecognized Type: [null]

### ISSUE THREAD

**Issue by rwijngaa** [swagger-api/swagger-samples#52]
Hi,

I'm porting my Play app from 2.3 to 2.4 (and using Guice to do DI) and i'm getting the 
> Error injecting constructor, java.lang.IllegalArgumentException: Unrecognized Type: [null]
at startup.

I updated my dependencies from
   ```
 "com.wordnik" %% "swagger-play2" % "1.3.13" exclude("org.reflections", "reflections"),
    "org.reflections" % "reflections" % "0.9.8" notTransitive()
```
to 
  ```
"io.swagger" %% "swagger-play2" % "1.5.1",
  "io.swagger" % "swagger-parser" % "1.0.16",
```

and added 
`play.modules.enabled += "play.modules.swagger.SwaggerModule"`

Note: i removed "@ApiImplicitParams" because i thought that was causing it, but to no avail.

```
1) Error injecting constructor, java.lang.IllegalArgumentException: Unrecognized Type: [null]
  at play.modules.swagger.SwaggerPluginImpl.<init>(SwaggerPlugin.scala:33)
  while locating play.modules.swagger.SwaggerPluginImpl
  at play.modules.swagger.SwaggerModule.bindings(SwaggerModule.scala:11):
Binding(interface play.modules.swagger.SwaggerPlugin to ConstructionTarget(class play.modules.swagger.SwaggerPluginImpl) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating play.modules.swagger.SwaggerPlugin

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[guice.jar:na]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184) ~[guice.jar:na]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[guice.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice.jar:na]
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153) ~[play-server_2.11-2.4.6.jar:2.4.6]
Caused by: java.lang.IllegalArgumentException: Unrecognized Type: [null]
	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:405) ~[jackson-databind.jar:2.5.4]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:354) ~[jackson-databind.jar:2.5.4]
	at com.fasterxml.jackson.databind.ObjectMapper.constructType(ObjectMapper.java:1332) ~[jackson-databind.jar:2.5.4]
	at io.swagger.scala.converter.SwaggerScalaModelConverter.resolveProperty(SwaggerScalaModelConverter.scala:32) ~[swagger-scala-module_2.11-1.0.0.jar:1.0.0]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79) ~[swagger-core-1.5.6.jar:1.5.6]
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58) ~[swagger-core-1.5.6.jar:1.5.6]
	at play.modules.swagger.PlayReader.createProperty(PlayReader.java:667) ~[swagger-play2_2.11-1.5.1.jar:1.5.1]
	at play.modules.swagger.PlayReader.getParameters(PlayReader.java:591) ~[swagger-play2_2.11-1.5.1.jar:1.5.1]
	at play.modules.swagger.PlayReader.parseMethod(PlayReader.java:514) ~[swagger-play2_2.11-1.5.1.jar:1.5.1]
	at play.modules.swagger.PlayReader.read(PlayReader.java:136) ~[swagger-play2_2.11-1.5.1.jar:1.5.1]
```

**Comment by rwijngaa** [comment]
see https://github.com/swagger-api/swagger-play/issues/43
