### ISSUE TITLE
The Mule sample doesn't work as application

### ISSUE THREAD

**Issue by iushankin** [swagger-api/swagger-samples#6]
From the Mule log:

```
ERROR 2015-07-02 13:07:04,410 [WrapperListener_start_runner] org.mule.module.launcher.application.DefaultMuleApplication: null
org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:101) ~[?:?]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:57) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1451) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1159) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) ~[?:?]
```

**Comment by webron** [comment]
@iushankin - can you explain how you ran it that you got this error?

**Comment by webron** [comment]
IIRC, this is not really an issue.
